### ISSUE TITLE
Request for blog post 

### ISSUE THREAD

**Issue by vishal71292** [hfiref0x/WDExtract#4]
Hello hfiref0x,

I am reading through your blogs https://swapcontext.blogspot.com/2019/11/introduction.html

I wanted you to make one more blog post on "WDExtract - Journey", where i am expecting to learn the path you used to reverse the vdm files and how the base structures for RMDX was reversed ?

P.S.
Sorry for using git issues for raising this request, since i dont have any mode of reaching you. Thanks for your excellent works.

**Comment by hfiref0x** [comment]
Hello,

I'm not using blogspot platform from 2022, so I cannot fulfil your request.

However I can answer on your question, the primary source of this extractor is a mpengine.dll from Windows Defender. RMDX format is not documented and what was reversed is just a small part required for unpacking database files.

**Comment by vishal71292** [comment]
Well in that case I have 2 more questions 

1. I started with mpengine.dll but struck with core data structure reversing. How did you reversed the structures and your trial and errors.
2. If you decided not to use blogpost is there any alternative place you are posting your thoughts ?

**Comment by hfiref0x** [comment]
It's been sooo long time ago so I cannot tell you exact path of analysis. You can refer to this https://github.com/commial/experiments/tree/master/windows-defender/VDM it does the same thing, and additionally describes "delta" files and their handling.

There are no other accounts, blogs, or what so ever, only fakes like this one for example @DiabloNova. Currently I have absolutely no time for this and doubt this will change in near perspective.

**Comment by vishal71292** [comment]
Got it, Thanks for taking your time to answer my queries 🙏 . Let me close this topic.
